name: GamblingSkyblock
version: '1.0-SNAPSHOT'
main: dev.melncat.gamblingtowers.GamblingTowers
api-version: '1.21'
authors: [ MelnCat ]
dependencies: 
  server: 
    Multiverse-Core:
      load: BEFORE
      required: true